### ISSUE TITLE
Issue with zero divisor

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework6G5#20]
@poojashresthacode I found somewhere that you are struggling to resolve the RuntimeWarning: divide by zero encountered in divide
  return np.where(x !=0, np.cos(1/x),0). I have sent to this group a merge request regarding this issue. You can take that code as a reference.

**Comment by poojashresthacode** [comment]
Yeah, I already resolved that. Your efforts are much appreciated.

**Comment by tirthbha** [comment]
Thank you
