### ISSUE TITLE
Dealing with Division by zero ERROR in task 1.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework6G5#48]
For task 1 how have you guys worked around cos(1/0) and exp(-1/0)?

**Comment by poojashresthacode** [comment]
I have used one boundary condition for each function. You can view the task one file . we have written a code to manage the zero division error

**Comment by Pranjal-Srivastava-2023** [comment]
I will check it out thanks!
