### ISSUE TITLE
hw6 documentation

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework6G5#5]
So the task assignment does not include the documentation part. Do we have to do that? If yes, Whose role could be it?

**Comment by WildJimmy** [comment]
I am also wondering this. It's sort of covered by task 3 (since they have to add docstrings), but the explicit documentation isn't covered anywhere

**Comment by reshnashrestha** [comment]
Yes, I tried to re confirm and prof said that we have to summarize our results in each task. So it’s like documenting individually.
